# Generated by Django 4.1.7 on 2023-04-23 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "notesapp",
            "0002_remove_archive_edit_date_remove_archive_publish_date_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Archive",
        ),
    ]
